from typing import Protocol, runtime_checkable

import torch

from asr.data.dataset import Batch


@runtime_checkable
class System(Protocol):
    training: bool

    def train_step(self, batch: Batch) -> torch.Tensor: ...
    def eval_step(self, batch: Batch) -> list[dict]: ...
    def parameters(self) -> list[torch.Tensor]: ...
    def to(self, device): ...
    def train(self, mode: bool = True) -> "System": ...
    def eval(self) -> "System": ...
